import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Provider/theme-provider";
import Navbar from "@/components/custom/Navbar";
import Footer from "@/components/custom/Footer";
import { Toaster } from "@/components/ui/sonner";
import { NextProvider } from "@/redux/NextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <div className=" min-h-[80vh] ">
              <div className="max-w-screen-xl flex flex-wrap items-center  justify-between mx-auto p-4">
                {children}
              </div>
            </div>

            <Toaster />
            <Footer />
          </ThemeProvider>
        </NextProvider>
      </body>
    </html>
  );
}
